name: Notifiction apres merge

on:
  workflow_run:
    workflows: ["Notification PR Mergée"]
    types:
      - completed

jobs:
  display_after_message:
    runs-on: ubuntu-latest
    steps:
      - name: "Message de resussite du workflow de merge"
        run: echo "Le workflow de merge est terminé !"